// _SwarmInterface_EOArchive.java
// Generated by EnterpriseObjects palette at Thursday, February 06, 2003 15:04:00 US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _SwarmInterface_EOArchive extends com.webobjects.eoapplication.EOArchive {
    SliderCell _sliderCell0, _sliderCell1, _sliderCell2;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _nsTextField0;
    javax.swing.JButton _nsButton0;
    javax.swing.JCheckBox _nsButton1;
    javax.swing.JPanel _nsView0, _nsView1;

    public _SwarmInterface_EOArchive(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel1");
        _nsView1 = (JPanel)_eoFrame1.getContentPane();
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("About This Simulation"), "NSButton");
        _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Automatic camera control"), "NSButton4");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 8, 8), "");
        _sliderCell2 = (SliderCell)_registered(new SliderCell(), "");
        _sliderCell1 = (SliderCell)_registered(new SliderCell(), "");
        _sliderCell0 = (SliderCell)_registered(new SliderCell(), "NSSlider2");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(3, 1, 4, 7), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "InterfaceWindow");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("This breve demo simulation shows an example of how custom interface elements can be added to simulations.\n\nYou can make your own starting with the Template nib file which comes with the breve distribution.  Use this template, along with the Interface Builder application (included with the Mac OS X developer tools) to build an interface window for your simulation.\n\nFor each interface element, you will need to assign a unique numerical tag inside the Interface Builder inspector window.  This number will be used by the breve simulation to identify the button or control being used.  See the Tips & Techniques file for more information!");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(326, 200);
        _nsTextField0.setLocation(11, 14);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField0);
        _nsView1.setSize(346, 228);
        _eoFrame1.setTitle("About This Simulation");
        _eoFrame1.setLocation(362, 292);
        _eoFrame1.setSize(346, 228);
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_eoFrame1, "makeKeyAndOrderFront", _nsButton0), ""));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Lucida Grande", 10, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 10, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Lucida Grande", 10, Font.PLAIN);
        _eoTextField0.setSize(81, 14);
        _eoTextField0.setLocation(0, 0);
        _nsMatrix1.add(_eoTextField0);
        _eoTextField1.setSize(81, 14);
        _eoTextField1.setLocation(0, 22);
        _nsMatrix1.add(_eoTextField1);
        _eoTextField2.setSize(81, 14);
        _eoTextField2.setLocation(0, 44);
        _nsMatrix1.add(_eoTextField2);
        _setFontForComponent(_sliderCell2, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_sliderCell1, "Helvetica", 12, Font.PLAIN);
        _setFontForComponent(_sliderCell0, "Helvetica", 12, Font.PLAIN);
        _sliderCell0.setSize(131, 17);
        _sliderCell0.setLocation(0, 0);
        _nsMatrix0.add(_sliderCell0);
        _sliderCell1.setSize(131, 17);
        _sliderCell1.setLocation(0, 24);
        _nsMatrix0.add(_sliderCell1);
        _sliderCell2.setSize(131, 17);
        _sliderCell2.setLocation(0, 48);
        _nsMatrix0.add(_sliderCell2);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(132, 65);
        _nsMatrix0.setLocation(102, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsMatrix1.setSize(82, 58);
        _nsMatrix1.setLocation(13, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix1);
        _nsButton1.setSize(185, 17);
        _nsButton1.setLocation(31, 86);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsButton0.setSize(173, 26);
        _nsButton0.setLocation(37, 140);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(246, 176);
            _eoFrame0.setTitle("Swarm");
            _eoFrame0.setLocation(50, 219);
            _eoFrame0.setSize(246, 176);
        }
    }
}
