SRC	+= kernel/breveEval.cc kernel/breveObjectAPI.cc kernel/callback.cc \
		kernel/color.cc kernel/engine.cc kernel/evalData.cc \
		kernel/evalHash.cc kernel/evalList.cc kernel/frontendAPI.cc \
		kernel/interface.cc kernel/internal.cc \
		kernel/internalFunctions/breveFunctionsCamera.cc \
		kernel/internalFunctions/breveFunctionsControl.cc \
		kernel/internalFunctions/breveFunctionsDrawing.cc \
		kernel/internalFunctions/breveFunctionsFile.cc \
		kernel/internalFunctions/breveFunctionsGraph.cc \
		kernel/internalFunctions/breveFunctionsImage.cc \
		kernel/internalFunctions/breveFunctionsJoint.cc \
		kernel/internalFunctions/breveFunctionsLink.cc \
		kernel/internalFunctions/breveFunctionsReal.cc \
		kernel/internalFunctions/breveFunctionsMath.cc \
		kernel/internalFunctions/breveFunctionsMatrix.cc \
		kernel/internalFunctions/breveFunctionsVector.cc \
		kernel/internalFunctions/breveFunctionsStatistics.cc \
		kernel/internalFunctions/breveFunctionsMenu.cc \
		kernel/internalFunctions/breveFunctionsMovie.cc \
		kernel/internalFunctions/breveFunctionsMultibody.cc \
		kernel/internalFunctions/breveFunctionsNetwork.cc \
		kernel/internalFunctions/breveFunctionsNeuralNetwork.cc \
		kernel/internalFunctions/breveFunctionsNeural.cc \
		kernel/internalFunctions/breveFunctionsObject.cc \
		kernel/internalFunctions/breveFunctionsPatches.cc \
		kernel/internalFunctions/breveFunctionsPhysics.cc \
		kernel/internalFunctions/breveFunctionsPush.cc \
		kernel/internalFunctions/breveFunctionsPushCallback.cc \
		kernel/internalFunctions/breveFunctionsQGAME.cc \
		kernel/internalFunctions/breveFunctionsShape.cc \
		kernel/internalFunctions/breveFunctionsSound.cc \
		kernel/internalFunctions/breveFunctionsSpring.cc \
		kernel/internalFunctions/breveFunctionsStationary.cc \
		kernel/internalFunctions/breveFunctionsTerrain.cc \
		kernel/internalFunctions/breveFunctionsWorld.cc \
		kernel/multithread.cc kernel/namespace.cc kernel/network.cc \
		kernel/plugins.cc kernel/sound.cc 
