all: 
	-(cd slQTMusicPlugin && $(MAKE))
	-(cd slDigitizerPlugin && $(MAKE))
	-(cd slRegexPlugin && $(MAKE))
	-(cd slURLPlugin && $(MAKE))
	-(cd samples && $(MAKE))

clean: 
	-(cd slQTMusicPlugin && $(MAKE) clean)
	-(cd slDigitizerPlugin && $(MAKE) clean)
	-(cd slRegexPlugin && $(MAKE) clean)
	-(cd slURLPlugin && $(MAKE) clean)
	-(cd samples && $(MAKE) clean)
