all: 
	-(cd slQTMusicPlugin && make)
	-(cd slDigitizerPlugin && make)
	-(cd slRegexPlugin && make)
	-(cd slURLPlugin && make)
	-(cd slJavaPlugin && make)

clean: 
	-(cd slQTMusicPlugin && make clean)
	-(cd slDigitizerPlugin && make clean)
	-(cd slRegexPlugin && make clean)
	-(cd slURLPlugin && make clean)
	-(cd slJavaPlugin && make clean)
