HEADERS += util/error.h util/hash.h util/list.h util/matrix.h util/memory.h \
		util/nr.h util/quat.h util/stack.h util/stringstream.h \
		util/text.h util/util.h util/utilTypedefs.h util/vector.h
SRC	+= util/error.cc util/hash.cc util/list.cc util/matrix.cc \
		util/memory.cc util/nr.cc util/quat.cc util/stack.cc \
		util/stringstream.cc util/text.cc util/time.cc util/vector.cc
