// _breveSwarm_EOArchive_English.java
// Generated by EnterpriseObjects palette at Tuesday, March 11, 2003 11:48:12 US/Eastern

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _breveSwarm_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0, _nsMatrix1;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _nsTextField0, _nsTextField1, _nsTextField2;
    com.webobjects.eointerface.swing.EOView _nsColorWell0, _nsColorWell1;
    javax.swing.JButton _nsButton0, _nsButton1;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView0;

    public _breveSwarm_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsMatrix1 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 1, 8, 8), "NSMatrix1");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(1, 1, 8, 8), "NSMatrix");
        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Learn more about breve"), "NSButton");
        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Save"), "NSButton1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "flockBehaviorPopup")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "skyColor")) != null)) {
            _nsColorWell1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell1");
        } else {
            _nsColorWell1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "21");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cloudColor")) != null)) {
            _nsColorWell0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsColorWell0");
        } else {
            _nsColorWell0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "configWindow")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "openBreveHomepage", _nsButton1), ""));
        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "closeSheet", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Obedient");
            _popup0.addItem("Normal");
            _popup0.addItem("Wacky");
            _popup0.addItem("Surprise Me");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "flockBehaviorPopup");
        }

        if (_replacedObjects.objectForKey("_nsColorWell1") == null) {
            _connect(_owner(), _nsColorWell1, "skyColor");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "configWindow");
        }

        if (_replacedObjects.objectForKey("_nsColorWell0") == null) {
            _connect(_owner(), _nsColorWell0, "cloudColor");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField2, "Arial Black", 24, Font.PLAIN + Font.BOLD);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("breveSwarm 1.5");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("by Jon Klein");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Flocking Style\n");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 13, Font.PLAIN);
        _eoTextField1.setSize(91, 17);
        _eoTextField1.setLocation(0, 0);
        _nsMatrix1.add(_eoTextField1);
        _setFontForComponent(_eoTextField0, "Lucida Grande", 13, Font.PLAIN);
        _eoTextField0.setSize(91, 17);
        _eoTextField0.setLocation(0, 0);
        _nsMatrix0.add(_eoTextField0);
        _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsColorWell0.setSize(53, 30);
        _nsColorWell0.setLocation(13, 190);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsColorWell0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsColorWell0);
        _nsButton0.setSize(77, 26);
        _nsButton0.setLocation(244, 318);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsMatrix0.setSize(92, 17);
        _nsMatrix0.setLocation(71, 196);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix0);
        _nsColorWell1.setSize(53, 30);
        _nsColorWell1.setLocation(13, 228);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsColorWell1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsColorWell1);
        _nsMatrix1.setSize(92, 17);
        _nsMatrix1.setLocation(71, 234);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsMatrix1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsMatrix1);
        _popup0.setSize(121, 26);
        _popup0.setLocation(15, 286);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsTextField0.setSize(79, 14);
        _nsTextField0.setLocation(11, 266);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField0);
        _nsButton1.setSize(213, 26);
        _nsButton1.setLocation(65, 148);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton1);
        _nsTextField1.setSize(62, 14);
        _nsTextField1.setLocation(224, 33);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsImageView0.setSize(101, 100);
        _nsImageView0.setLocation(115, 41);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsImageView0);
        _nsTextField2.setSize(223, 39);
        _nsTextField2.setLocation(63, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(330, 354);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(934, 396);
            _eoFrame0.setSize(330, 354);
        }
    }
}
