SRC	+= simulation/image.cc simulation/integrate.cc \
		simulation/joint.cc simulation/lightdetector.cc \
		simulation/link.cc simulation/movie.cc simulation/multibody.cc \
		simulation/netsim.cc simulation/patch.cc simulation/shadowvolume.cc \
		simulation/sensor.cc simulation/shape.cc simulation/springs.cc \
		simulation/terrain.cc simulation/tiger.cc simulation/vclip.cc \
		simulation/vclipData.cc simulation/volInt.cc \
		simulation/world.cc simulation/worldObject.cc \
		simulation/roam.cc simulation/mesh.cc simulation/fonts.cc \
		simulation/camera.cc simulation/drawcommand.cc \
		simulation/texture.cc simulation/skybox.cc \
		simulation/gldraw.cc
