HEADERS += simulation/asciiart.h simulation/camera.h simulation/drawcommand.h \
		simulation/glIncludes.h simulation/gldraw.h simulation/image.h \
		simulation/integrate.h simulation/joint.h \
		simulation/lightdetector.h simulation/link.h \
		simulation/movie.h simulation/multibody.h simulation/netsim.h \
		simulation/patch.h simulation/shadow.h simulation/shape.h \
		simulation/shared_ptr.h simulation/simulation.h \
		simulation/simulationTypedefs.h simulation/springs.h \
		simulation/terrain.h simulation/tiger.h simulation/vclip.h \
		simulation/vclipData.h simulation/volInt.h simulation/world.h \
		simulation/worldObject.h
SRC	+= simulation/camera.cc simulation/drawcommand.cc simulation/gldraw.cc \
		simulation/image.cc simulation/integrate.cc \
		simulation/joint.cc simulation/lightdetector.cc \
		simulation/link.cc simulation/movie.cc simulation/multibody.cc \
		simulation/netsim.cc simulation/patch.cc simulation/shadow.cc \
		simulation/shape.cc simulation/springs.cc \
		simulation/terrain.cc simulation/tiger.cc simulation/vclip.cc \
		simulation/vclipData.cc simulation/volInt.cc \
		simulation/world.cc simulation/worldObject.cc
