/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Breve.xs. Do not edit this file, edit Breve.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Breve.xs"
#ifdef __cplusplus
extern "C" {
#endif
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "ppport.h"
#ifdef __cplusplus
}
#endif

#include "perlInterface.h"

#line 24 "Breve.c"

XS(XS_Breve_brPerlSetController); /* prototype to pass -Wmissing-prototypes */
XS(XS_Breve_brPerlSetController)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Breve::brPerlSetController(alpha, beta)");
    {
	void*	alpha = INT2PTR(void *,SvIV(ST(0)));
	void*	beta = INT2PTR(void *,SvIV(ST(1)));
	void *	RETVAL;
	dXSTARG;

	RETVAL = brPerlSetController(alpha, beta);
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Breve_testingfoo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Breve_testingfoo)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Breve::testingfoo()");
    {
#line 22 "Breve.xs"
		printf("testingfoo called.\n");
#line 54 "Breve.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Breve_blahblah); /* prototype to pass -Wmissing-prototypes */
XS(XS_Breve_blahblah)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Breve::blahblah()");
    {

	blahblah();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Breve); /* prototype to pass -Wmissing-prototypes */
XS(boot_Breve)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Breve::brPerlSetController", XS_Breve_brPerlSetController, file);
        newXS("Breve::testingfoo", XS_Breve_testingfoo, file);
        newXS("Breve::blahblah", XS_Breve_blahblah, file);

    /* Initialisation Section */

#line 27 "Breve.xs"
	printf("Hello from the bootstrap!\n");

#line 93 "Breve.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

