SRC	+= steve/format.cc steve/stevelex.c steve/steveparse.tab.c \
		steve/breveFunctionsSteveDataObject.cc \
		steve/breveFunctionsSteveObject.cc \
		steve/breveFunctionsSteveXML.cc steve/dataObject.cc \
		steve/evalListSort.cc steve/evaluation.cc \
		steve/expression.cc steve/gc.cc steve/genetic.cc \
		steve/interactive.cc steve/object.cc steve/steveFrontend.cc \
		steve/stringexp.cc steve/xml.cc steve/pyconvert.cc

steve/steveparse.tab.h: steve/steveparse.tab.c
