SRC	+= steve/format.c steve/stevelex.c steve/steveparse.tab.c \
		steve/breveFunctionsSteveDataObject.c \
		steve/breveFunctionsSteveObject.c \
		steve/breveFunctionsSteveXML.c steve/dataObject.c \
		steve/evalListCopyGC.c steve/evalListSort.c steve/evaluation.c \
		steve/expression.c steve/gc.c steve/genetic.c \
		steve/interactive.c steve/object.c steve/steveFrontend.c \
		steve/stringexp.c steve/xml.c

steve/steveparse.tab.h: steve/steveparse.tab.c
	cp $@ include/breve/
