HEADERS += steve/breveFunctionsSteveDataObject.h \
		steve/breveFunctionsSteveObject.h \
		steve/breveFunctionsSteveXML.h steve/dataObject.h \
		steve/evalListCopyGC.h steve/evalListSort.h steve/evaluation.h \
		steve/expression.h steve/gc.h steve/genetic.h \
		steve/interactive.h steve/object.h steve/steve.h \
		steve/steveFrontend.h steve/steveTypedefs.h steve/steveparse.h \
		steve/steveparse.tab.h steve/stringexp.h steve/xml.h
SRC	+= steve/format.c steve/stevelex.c steve/steveparse.tab.c \
		steve/breveFunctionsSteveDataObject.c \
		steve/breveFunctionsSteveObject.c \
		steve/breveFunctionsSteveXML.c steve/dataObject.c \
		steve/evalListCopyGC.c steve/evalListSort.c steve/evaluation.c \
		steve/expression.c steve/gc.c steve/genetic.c \
		steve/interactive.c steve/object.c steve/steveFrontend.c \
		steve/stringexp.c steve/xml.c

steve/steveparse.tab.h: steve/steveparse.tab.c
